apiVersion: v1
kind: Service
metadata:
  name: ophelia-ci-interface-deployment
spec:
  type: NodePort
  selector:
    app: ophelia-ci-interface
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
