apiVersion: v1
kind: Service
metadata:
  name: one-pod-node-port
spec:
  type: NodePort
  selector:
    app: ophelia-ci-one-pod
  ports:
  - port: 8000
    name: interface
    targetPort: 8000
    nodePort: 30300
  - port: 50051
    name: server
    targetPort: 50051
    nodePort: 30330
