apiVersion: v1
kind: Service
metadata:
  name: server-node-port-service
spec:
  type: NodePort
  selector:
    app: ophelia-ci-server
  ports:
  - port: 50051
    targetPort: 50051
    nodePort: 30030
